-- This module is the root of the GeometricLanglandsCanonicalLaneLean Lean proof package.
import GeometricLanglandsCanonicalLaneLean.Basic
import GeometricLanglandsCanonicalLaneLean.SourcePackage
import GeometricLanglandsCanonicalLaneLean.SourceDependencies
import GeometricLanglandsCanonicalLaneLean.Formalization
import GeometricLanglandsCanonicalLaneLean.ReviewerBridge
import GeometricLanglandsCanonicalLaneLean.TheoremStatement
import GeometricLanglandsCanonicalLaneLean.MathlibObjects
import GeometricLanglandsCanonicalLaneLean.AdmissibleClass
import GeometricLanglandsCanonicalLaneLean.Projection
import GeometricLanglandsCanonicalLaneLean.BridgeLemmas
import GeometricLanglandsCanonicalLaneLean.GateLemmas
import GeometricLanglandsCanonicalLaneLean.FinalTheorem
import GeometricLanglandsCanonicalLaneLean.MathlibStatement
